config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => "home_pages#index"
  resources :link_wordings
  resources :url_imports
  resources :product_infos
  resources :brand_infos
  post 'product_search', :to => 'product_infos#search'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
end

app/models/csv_upload.rb
class CsvUpload < ActiveRecord::Base
	mount_uploader :file, CsvUploader

  validates :file, presence: true
end

app/models/f_product.rb
class FProduct < FetDbConnecter
	self.table_name = "products"
  self.primary_key = "id"
end

app/models/fet_brand_url.rb
class FetBrandUrl < ActiveRecord::Base
  belongs_to :brand, :class_name => "Brand", :foreign_key => "brand_id"
end

app/models/fet_db_connecter.rb
class FetDbConnecter < ActiveRecord::Base
  # see
  # http://stackoverflow.com/questions/6122508/connecting-rails-3-1-with-multiple-databases
  self.abstract_class = true
  establish_connection :fet_db
end

app/models/fet_link_wording.rb
class FetLinkWording < ActiveRecord::Base
end

app/models/fet_product_url.rb
class FetProductUrl < ActiveRecord::Base
end

app/models/product_fet_ship.rb
class ProductFetShip < ActiveRecord::Base
end

app/models/user.rb
class User < FetDbConnecter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  self.table_name = "users"
  self.primary_key = "id"
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  layout "fet_diversion", :except => [:new]
end

app/controllers/brand_infos_controller.rb
class BrandInfosController < ApplicationController
	def index
		@fet_brands = FetBrandUrl.all.order("updated_at asc")
	end
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
	def index
	end
end

app/controllers/link_wordings_controller.rb
class LinkWordingsController < ApplicationController
	def index
		@wording = FetLinkWording.first
	end

	def edit
		@wording = FetLinkWording.first
	end

	def update
		@wording = FetLinkWording.first
		@wording.update(event_params)
	  redirect_to :action => :index
	end

	private

	def event_params
	  params.require(:fet_link_wording).permit(:review_wording, :product_wording, :brand_wording)
	end

end

app/controllers/product_infos_controller.rb
class ProductInfosController < ApplicationController
	def index
		@fet_products = FetProductUrl.find_by_sql("select * from fet_product_urls INNER JOIN product_fet_ships ON product_fet_ships.guid = fet_product_urls.guid ORDER BY fet_product_urls.updated_at asc limit 30")
	end

	def search
		@fet_products = FetProductUrl.find_by_sql(["select * from fet_product_urls INNER JOIN product_fet_ships ON product_fet_ships.guid = fet_product_urls.guid where fet_product_urls.guid like ? or fet_product_urls.name like ?", "%#{params[:keyword]}%", "%#{params[:keyword]}%"])
	end
end

app/controllers/url_imports_controller.rb
# -*- coding: UTF-8 -*-
class UrlImportsController < ApplicationController
	require 'csv'
	skip_before_filter  :verify_authenticity_token

	def index
	end

  def create
  	cvs_upload = CsvUpload.new
  	cvs_upload.file = url_params
    cvs_upload.save!
    ic = Iconv.new("utf-8", "big5")
    csv_text = params[:data_file].tempfile
    csv = CSV.parse(csv_text, :headers => true)
    ary = Array.new
    null_product = Array.new
    guid_product = Array.new
    csv.each do |item|
      p ic.iconv(item[0])
      p "0000"
      cn = 0
      item.each_with_index { |d,i| cn -= 1 if item[i] == ( "" and nil)} 
      cp = FProduct.find_by_id(item[1].to_i) 
      if cn == 0 && cp.present?
      	check_product = FetProductUrl.find_by_guid(item[1].to_i)
      	check_product.destroy if check_product.present?
      	product_url = FetProductUrl.new
      	product_url.name = ic.iconv(item[0].to_s)
      	product_url.guid = item[1].to_i
      	product_url.product_pc_url = item[2].to_s
      	product_url.product_mobi_url = item[3].to_s
      	product_url.review_pc_url = item[4].to_s
      	product_url.review_mobi_url = item[5].to_s
      	product_url.status = item[6].to_i
      	product_url.save!
        cps = ProductFetShip.find_by_product_id(cp.product_id)
        cps.destroy if cps.present?
        product_fet_ship = ProductFetShip.new
        product_fet_ship.product_id = cp.product_id
        product_fet_ship.guid = item[1].to_i
        product_fet_ship.save!
      	ary << ic.iconv(item[0].to_s)
      else
        null_product << ic.iconv(item[0].to_s) if cn != 0
        guid_product << ic.iconv(item[0].to_s) if cp.blank?
      end
    end
    @product_info = ary
    @null_product = null_product
    @guid_product = guid_product

    render :action => "index"
  end
  def url_params
    params.require(:data_file)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brand_infos_helper.rb
module BrandInfosHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/link_wordings_helper.rb
module LinkWordingsHelper
end

app/helpers/product_infos_helper.rb
module ProductInfosHelper
end

app/helpers/url_imports_helper.rb
module UrlImportsHelper
end

app/views/brand_infos/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">既有品牌資訊</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
<div class="col-lg-12">
  <div class="well">*需由手機王手動執行更新</div>
</div>
<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">品牌列表</div>
    <!-- /.panel-heading -->
    <div class="panel-body">
      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <th>#</th>
              <th>brand</th>
              <th>路徑(電腦)</th>
              <th>路徑(手機)</th>
              <th>狀態</th>
            </tr>
          </thead>
          <tbody>
          	<% @fet_brands.each do |fet_brand|%>
	            <tr>
	              <td><%= fet_brand.id %></td>
	              <td><%= fet_brand.brand.name_normal %></td>
	              <td><%= fet_brand.pc_url %></td>
	              <td><%= fet_brand.mobi_url%></td>
	              <td><%= fet_brand.status %></td>
	            </tr>
	          <% end %>
          </tbody>
        </table>
      </div>
      <!-- /.table-responsive -->
    </div>
    <!-- /.panel-body -->
  </div>
  <!-- /.panel -->
</div>

app/views/home_pages/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Dashboard</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
<div class="row">
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-send-o fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge">__</div>
            <div>產品路徑匯入</div>
          </div>
        </div>
      </div>
      <a href="/url_imports">
        <div class="panel-footer">
          <span class="pull-left">View Details</span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
  <div class="col-lg-3 col-md-6">
	  <div class="panel panel-green">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-info fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge">__</div>
            <div>既有產品資訊</div>
          </div>
        </div>
      </div>
      <a href="/product_infos">
        <div class="panel-footer">
          <span class="pull-left">View Details</span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      </a>
	  </div>
  </div>
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-yellow">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-file-word-o fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge">__</div>
            <div>頁面文案調整</div>
          </div>
        </div>
      </div>
        <a href="/link_wordings">
            <div class="panel-footer">
                <span class="pull-left">View Details</span>
                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                <div class="clearfix"></div>
            </div>
        </a>
    </div>
  </div>
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-red">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-home fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge">__</div>
            <div>手機王首頁</div>
          </div>
        </div>
      </div>
      <a href="https://www.sogi.com.tw" target="_blank">
        <div class="panel-footer">
          <span class="pull-left">View Details</span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
</div>

app/views/link_wordings/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">頁面文案調整</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
<div class="col-lg-12">
  <div class="well">*文案內容有異動時，手機王頁面會即時更新</div>
</div>
<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      頁面文案
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
    	<div class="table-responsive">
        <%= form_for @wording, :url => link_wording_path(@wording.id) do |f| %>
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <th>#</th>
              <th>位置</th>
              <th>文案</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>產品內容頁</td>
              <td><%=f.text_field :product_wording,class: "form-control" %><font color="red">*最長不超過 6 個字數，含中英文、數字及符號<font></td>
            </tr>
            <tr>
              <td>2</td>
              <td>新聞頁</td>
              <td><%= f.text_field :review_wording,class: "form-control" %><font color="red">*最長不超過 42 個字數，含中英文、數字及符號<font></td>
            </tr>
            <tr>
              <td>3</td>
              <td>品牌頁</td>
              <td><%= f.text_field :brand_wording,class: "form-control" %><font color="red">*最長不超過 6 個字數，含中英文、數字及符號<font></td>
            </tr>
          </tbody>
        </table>
        <%= f.submit "Update", class: "btn btn-primary" %>
        <% end %>
    	</div>
    </div>
    <!-- /.panel-body -->
  </div>
  <!-- /.panel -->
</div>
<!-- /.col-lg-12 -->

app/views/link_wordings/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">頁面文案調整</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
<div class="col-lg-12">
  <div class="well">*文案內容有異動時，手機王頁面會即時更新</div>
</div>
<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      頁面文案 | <%= link_to "<button type='button' class='btn btn-edit'>edit</button>".html_safe, edit_link_wording_path(1)%>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
    	<div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <th>#</th>
              <th>位置</th>
              <th>文案</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>產品內容頁</td>
              <td><%= @wording.product_wording %></td>
            </tr>
            <tr>
              <td>2</td>
              <td>新聞頁</td>
              <td><%= @wording.review_wording %></td>
            </tr>
            <tr>
              <td>3</td>
              <td>品牌頁</td>
              <td><%= @wording.brand_wording %></td>
            </tr>
          </tbody>
        </table>
    	</div>
    </div>
    <!-- /.panel-body -->
  </div>
  <!-- /.panel -->
</div>
<!-- /.col-lg-12 -->
<div class="col-lg-6">
  <div class="panel panel-default">
    <div class="panel-heading">網頁查看</div>
    <!-- /.panel-heading -->
    <div class="panel-body">
      <div class="table-responsive">
        <table class="table">
          <tbody>
            <tr class="success">
              <td>產品內容頁</td>
              <td><a href="https://www.sogi.com.tw/products/12763" target="_blank">https://www.sogi.com.tw/products/12763</a></td>
            </tr>
            <tr class="info">
              <td>新聞頁</td>
              <td><a href="https://www.sogi.com.tw/articles/6248597" target="_blank">https://www.sogi.com.tw/articles/6248597</a></td>
            </tr>
            <tr class="warning">
              <td>品牌頁</td>
              <td><a href="https://www.sogi.com.tw/brands/Apple/116" target="_blank">https://www.sogi.com.tw/brands/Apple/116</a></td>
            </tr>
          </tbody>
        </table>
      </div>
      <!-- /.table-responsive -->
    </div>
    <!-- /.panel-body -->
  </div>
  <!-- /.panel -->
</div>

app/views/product_infos/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">既有產品資訊</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
<div class="col-lg-12">
  <div class="well">*產品比對建立或更新內容三小時後，手機王頁面才會更新</div>
</div>
<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">產品搜尋<i>(guid或是name)</i></div>
    <!-- /.panel-heading -->
    <div class="panel-body">  
      <%= form_tag product_search_path, :method => :post do  %>
        <div class="input-group custom-search-form">
          <%= text_field_tag "keyword", nil , :class => "form-control", :placeholder =>"Search..." %>
          <span class="input-group-btn">
            <%= button_tag(type: 'submit', class: "btn btn-default") do %>
              <i class="fa fa-search"></i>
            <% end %>
          </span>
        </div>
      <% end %>
    </div>
    <!-- /.panel-body -->
  </div>
  <!-- /.panel -->
</div>
<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">產品列表(最後更新 30 筆資料)</div>
    <!-- /.panel-heading -->
    <div class="panel-body">
      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <th>sogi_id</th>
              <th>guid</th>
              <th>Name</th>
              <th>產品路徑(電腦)</th>
              <th>產品路徑(手機)</th>
              <th>評測路徑(電腦)</th>
              <th>評測路徑(手機)</th>
              <th>狀態</th>
            </tr>
          </thead>
          <tbody>
          	<% @fet_products.each do |fet_product|%>
	            <tr>
                <td><%= fet_product.product_id %></td>
	              <td><%= fet_product.guid %></td>
	              <td><%= fet_product.name %></td>
	              <td><%= fet_product.product_pc_url %></td>
	              <td><%= fet_product.product_mobi_url%></td>
	              <td><%= fet_product.review_pc_url%></td>
	              <td><%= fet_product.review_mobi_url%></td>
	              <td><%= fet_product.status %></td>
	            </tr>
	          <% end %>
          </tbody>
        </table>
      </div>
      <!-- /.table-responsive -->
    </div>
    <!-- /.panel-body -->
  </div>
  <!-- /.panel -->
</div>

app/views/product_infos/search.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">搜尋結果</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
<div class="col-lg-12">
  <div class="well">*產品比對建立或更新內容三小時後，手機王頁面才會更新</div>
</div>
<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">產品搜尋<i>(guid或是name)</i></div>
    <!-- /.panel-heading -->
    <div class="panel-body">  
      <%= form_tag product_search_path, :method => :post do  %>
        <div class="input-group custom-search-form">
          <%= text_field_tag "keyword", nil , :class => "form-control", :placeholder =>"Search..." %>
          <span class="input-group-btn">
            <%= button_tag(type: 'submit', class: "btn btn-default") do %>
              <i class="fa fa-search"></i>
            <% end %>
          </span>
        </div>
      <% end %>
    </div>
    <!-- /.panel-body -->
  </div>
  <!-- /.panel -->
</div>
<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">產品列表</div>
    <!-- /.panel-heading -->
    <div class="panel-body">
      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <th>sogi_id</th>
              <th>guid</th>
              <th>Name</th>
              <th>產品路徑(電腦)</th>
              <th>產品路徑(手機)</th>
              <th>評測路徑(電腦)</th>
              <th>評測路徑(手機)</th>
              <th>狀態</th>
            </tr>
          </thead>
          <tbody>
          	<% @fet_products.each do |fet_product|%>
	            <tr>
                <td><%= fet_product.product_id %></td>
	              <td><%= fet_product.guid %></td>
	              <td><%= fet_product.name %></td>
	              <td><%= fet_product.product_pc_url %></td>
	              <td><%= fet_product.product_mobi_url%></td>
	              <td><%= fet_product.review_pc_url%></td>
	              <td><%= fet_product.review_mobi_url%></td>
	              <td><%= fet_product.status %></td>
	            </tr>
	          <% end %>
          </tbody>
        </table>
      </div>
      <!-- /.table-responsive -->
    </div>
    <!-- /.panel-body -->
  </div>
  <!-- /.panel -->
</div>

app/views/url_imports/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">產品路徑匯入</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
<%= "已成功匯入 >> #{@product_info}" if @product_info.present? %>
<br>
<%= "欄位有空值 >> #{@null_product}" if @null_product.present? %>
<br>
<%= "guid無法比對 >> #{@guid_product}" if @guid_product.present? %>
<div class="row">
  <div class="col-lg-12">
		<form method="post" action="<%= url_imports_path %>" enctype="multipart/form-data">
		  <%= csrf_meta_tag %>
		  <input class="form-control" type="file" name="data_file" accept=".csv">
		  <button type="submit" class="btn btn-primary" style="width: 120px">提交</button>
		</form>
	</div>
</div>