config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => "home_pages#index"
  resources :link_wordings
  resources :url_imports
  resources :product_infos
  resources :brand_infos
  post 'product_search', :to => 'product_infos#search'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
end

app/models/csv_upload.rb
class CsvUpload < ActiveRecord::Base
	mount_uploader :file, CsvUploader

  validates :file, presence: true
end

app/models/f_product.rb
class FProduct < FetDbConnecter
	self.table_name = "products"
  self.primary_key = "id"
end

app/models/fet_brand_url.rb
class FetBrandUrl < ActiveRecord::Base
  belongs_to :brand, :class_name => "Brand", :foreign_key => "brand_id"
end

app/models/fet_db_connecter.rb
class FetDbConnecter < ActiveRecord::Base
  # see
  # http://stackoverflow.com/questions/6122508/connecting-rails-3-1-with-multiple-databases
  self.abstract_class = true
  establish_connection :fet_db
end

app/models/fet_link_wording.rb
class FetLinkWording < ActiveRecord::Base
end

app/models/fet_product_url.rb
class FetProductUrl < ActiveRecord::Base
end

app/models/product_fet_ship.rb
class ProductFetShip < ActiveRecord::Base
end

app/models/user.rb
class User < FetDbConnecter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  self.table_name = "users"
  self.primary_key = "id"
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  layout "fet_diversion", :except => [:new]
end

app/controllers/brand_infos_controller.rb
class BrandInfosController < ApplicationController
	def index
		@fet_brands = FetBrandUrl.all.order("updated_at asc")
	end
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
	def index
	end
end

app/controllers/link_wordings_controller.rb
class LinkWordingsController < ApplicationController
	def index
		@wording = FetLinkWording.first
	end

	def edit
		@wording = FetLinkWording.first
	end

	def update
		@wording = FetLinkWording.first
		@wording.update(event_params)
	  redirect_to :action => :index
	end

	private

	def event_params
	  params.require(:fet_link_wording).permit(:review_wording, :product_wording, :brand_wording)
	end

end

app/controllers/url_imports_controller.rb
# -*- coding: UTF-8 -*-
class UrlImportsController < ApplicationController
	require 'csv'
	skip_before_filter  :verify_authenticity_token

	def index
	end

  def create
  	cvs_upload = CsvUpload.new
  	cvs_upload.file = url_params
    cvs_upload.save!
    ic = Iconv.new("utf-8", "big5")
    csv_text = params[:data_file].tempfile
    csv = CSV.parse(csv_text, :headers => true)
    ary = Array.new
    null_product = Array.new
    guid_product = Array.new
    csv.each do |item|
      p ic.iconv(item[0])
      p "0000"
      cn = 0
      item.each_with_index { |d,i| cn -= 1 if item[i] == ( "" and nil)} 
      cp = FProduct.find_by_id(item[1].to_i) 
      if cn == 0 && cp.present?
      	check_product = FetProductUrl.find_by_guid(item[1].to_i)
      	check_product.destroy if check_product.present?
      	product_url = FetProductUrl.new
      	product_url.name = ic.iconv(item[0].to_s)
      	product_url.guid = item[1].to_i
      	product_url.product_pc_url = item[2].to_s
      	product_url.product_mobi_url = item[3].to_s
      	product_url.review_pc_url = item[4].to_s
      	product_url.review_mobi_url = item[5].to_s
      	product_url.status = item[6].to_i
      	product_url.save!
        cps = ProductFetShip.find_by_product_id(cp.product_id)
        cps.destroy if cps.present?
        product_fet_ship = ProductFetShip.new
        product_fet_ship.product_id = cp.product_id
        product_fet_ship.guid = item[1].to_i
        product_fet_ship.save!
      	ary << ic.iconv(item[0].to_s)
      else
        null_product << ic.iconv(item[0].to_s) if cn != 0
        guid_product << ic.iconv(item[0].to_s) if cp.blank?
      end
    end
    @product_info = ary
    @null_product = null_product
    @guid_product = guid_product

    render :action => "index"
  end
  def url_params
    params.require(:data_file)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brand_infos_helper.rb
module BrandInfosHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/link_wordings_helper.rb
module LinkWordingsHelper
end

app/helpers/product_infos_helper.rb
module ProductInfosHelper
end

app/helpers/url_imports_helper.rb
module UrlImportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FetDiversion</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/fet_diversion.html.erb
<!DOCTYPE html>
<%#= render "/refinery/html_tag" %>
	<head>
    <meta charset="utf-8">
	  <meta http-equiv="X-UA-Compatible" content="IE=edge">
	  <meta name="viewport" content="width=device-width, initial-scale=1">
	  <meta name="description" content="">
	  <meta name="author" content="">
	  <title>Fet - Diversion</title>

	  <!-- Bootstrap Core CSS -->
	  <link href="/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

	  <!-- MetisMenu CSS -->
	  <link href="/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">

	  <!-- Timeline CSS -->
	  <link href="/dist/css/timeline.css" rel="stylesheet">

	  <!-- Custom CSS -->
	  <link href="/dist/css/sb-admin-2.css" rel="stylesheet">

	  <!-- Morris Charts CSS -->
	  <link href="/bower_components/morrisjs/morris.css" rel="stylesheet">

	  <!-- Custom Fonts -->
	  <link href="/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

	  <!-- jQuery -->
    <script src="/bower_components/jquery/dist/jquery.min.js"></script>
    <script src="/bower_components/jquery/dist/jquery_ujs.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="/bower_components/metisMenu/dist/metisMenu.min.js"></script>

    <!-- Morris Charts JavaScript -->
    <script src="/bower_components/raphael/raphael-min.js"></script>
    <script src="/bower_components/morrisjs/morris.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="/dist/js/sb-admin-2.js"></script>

	  <!--[if lt IE 9]>
	      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	  <![endif]-->
  </head>
	<body>
		<%= csrf_meta_tag %>
		<div id="wrapper">
			<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
				<div class="navbar-header">
			    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
			      <span class="sr-only">teddyswu</span>
			      <span class="icon-bar"></span>
			      <span class="icon-bar"></span>
			      <span class="icon-bar"></span>
			    </button>
			    <a class="navbar-brand" href="<%= root_path %>">Diversion Admin v2.0</a>
			  </div>
			  <ul class="nav navbar-top-links navbar-right">
			    <li class="dropdown">
			      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
			        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
			      </a>
			      <ul class="dropdown-menu dropdown-user">
			        <li><a href="/users/edit"><i class="fa fa-user fa-fw"></i> User Profile</a>
			        </li>
			        <li class="divider"></li>
			        <li><%= link_to('<i class="fa fa-sign-out fa-fw"></i> Logout'.html_safe, destroy_user_session_path, :method => :delete) %>
			        </li>
			      </ul>
			      <!-- /.dropdown-user -->
			    </li>
			    <!-- /.dropdown -->
			  </ul>
			  <div class="navbar-default sidebar" role="navigation">
			    <div class="sidebar-nav navbar-collapse">
			      <ul class="nav" id="side-menu">
			        <li>
			          <%= link_to "<i class='fa fa-send-o fa-fw'></i>產品路徑匯入".html_safe, url_imports_path %>
			        </li>
			        <li>
			          <%= link_to "<i class='fa fa-info fa-fw'></i>既有產品資訊".html_safe, product_infos_path %>
			        </li>
			        <li>
			          <%= link_to "<i class='fa fa-book fa-fw'></i>既有品牌資訊".html_safe, brand_infos_path %>
			        </li>
			        <li>
			          <%= link_to "<i class='fa fa-file-word-o fa-fw'></i>頁面文案調整".html_safe, link_wordings_path %>
			        </li>
			      </ul>
			    </div>
			    <!-- /.sidebar-collapse -->
			  </div>
			</nav>
			<div id="page-wrapper">
	  		<%= yield %>
	  	</div>
  		<!-- /#page-wrapper -->
		</div>
	  
	</body>
</html>